- name: bug
  color: d73a4a
  description: Algo parou de funcionar

- name: enhancement
  color: 2ea44f
  description: Nova funcionalidade

- name: tech-debt
  color: f9c513

- name: refactor
  color: 0366d6

- name: documentation
  color: 6f42c1

- name: priority:critical
  color: b60205

- name: priority:high
  color: d93f0b

- name: priority:medium
  color: fbca04

- name: priority:low
  color: 0e8a16

- name: release
  color: 48b601
  description: Versão liberada

- name: sync
  color: 43721d
  description: Sincronização
