name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch: # permite execução manual

env:
  REGISTRY: docker.io
  IMAGE_NAME: andresnascimento/t1000-bot

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@5b9cf3909b54a280b6df6eee035755eb1f2fd611

      - name: Log in to Docker Hub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@703896b4f30f62d53f5530a80bcdc589a3f702bc
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=ref,event=tag
            type=sha,format=short,prefix=

      - name: Build and push Docker image
        uses: docker/build-push-action@cb941d0b895b09c17fa011d41c411b33c752cf28
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
