name: Sync Labels

on:
  push:
    paths:
      - ".github/labels.yml"
  workflow_dispatch:

permissions:
  contents: read
  issues: write # 👈 ESSA LINHA RESOLVE

jobs:
  labels:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Sync labels
        uses: crazy-max/ghaction-github-labeler@573dd2fc64c1d56e47ff3e3d0e8807832591688f
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          exclude: ".*" # 👈 não remove labels existentes
