name: Sync Labels

on:
  push:
    paths:
      - ".github/labels.yml"
  workflow_dispatch:

permissions:
  contents: read
  issues: write # 👈 ESSA LINHA RESOLVE

jobs:
  labels:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Sync labels
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          delete: false

      - name: release
        color: 48b601
        description: Versão liberada
      - name: sync
        color: 43721d
        description: Sincronização
