name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Generate changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@548ef30a59758183549ee11ccb2c5e28f8545b0d
        with:
          configurationJson: |
            {
              "categories": [
                { "title": "🚀 Features", "labels": ["enhancement"] },
                { "title": "🐛 Fixes", "labels": ["bug"] },
                { "title": "🧹 Refactor", "labels": ["refactor"] }
              ]
            }

      - name: Create Release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64
        with:
          body: ${{ steps.changelog.outputs.changelog }}
