name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a

      - name: Generate changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@e996d773a759f3d545d46a1b7f696c7be617051b
        with:
          configurationJson: |
            {
              "categories": [
                { "title": "🚀 Features", "labels": ["enhancement"] },
                { "title": "🐛 Fixes", "labels": ["bug"] },
                { "title": "🧹 Refactor", "labels": ["refactor"] }
              ]
            }

      - name: Create Release
        uses: softprops/action-gh-release@5a6f51711ce2ba103b78f5e9550f810679f11e0e
        with:
          body: ${{ steps.changelog.outputs.changelog }}
