name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Generate changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@0e97c5a6c98cfbe9b73edec147b0abc8fc4523a0
        with:
          configurationJson: |
            {
              "categories": [
                { "title": "🚀 Features", "labels": ["enhancement"] },
                { "title": "🐛 Fixes", "labels": ["bug"] },
                { "title": "🧹 Refactor", "labels": ["refactor"] }
              ]
            }

      - name: Create Release
        uses: softprops/action-gh-release@77fb938f2f95e717ce6705d2909af527263360a0
        with:
          body: ${{ steps.changelog.outputs.changelog }}
